name: Check for new essays daily

on:
  schedule:
  - cron: "0 7 * * *" # Runs at 07:00 UTC everyday
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2 # Checkout the repository content to github runner.

      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.9 # Install the python version needed

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip requests
       

      - name: Execute application # Run the run.py to get the latest data
        run: |
          make all
